---
- hosts: localhost
  gather_facts: no
  tasks:
    - include_tasks: tasks/vpc_facts.yml
      tags: ['cleanup']
    - include_tasks: tasks/keypairs.yml
      tags: ['cleanup', 'git']
    - include_tasks: tasks/security_groups.yml
      tags: ['cleanup']
    - include_tasks: tasks/base_webserver_launch.yml

- hosts: webservers
  become: yes
  tasks:
    - include_tasks: tasks/env_setup.yml
    - include_tasks: tasks/docker_setup.yml