- name: Create base webserver instance
  ec2_instance:
    name: BaseWebserver
    tags:
      CreatedBy: Ansible
    instance_type: "{{ base_vm_type }}"
    image_id: "{{ default_amis.images[-1].image_id }}"
    key_name: webservers_key
    # If subnet ID is not given the module will choose the default zone of the default VPC
    # This makes most of the previous VPC fact gathering useless for this instance's purpose
    vpc_subnet_id: "{{ subnet_ids[0] }}"
    network:
      assign_public_ip: yes
    security_group: webservers_access
    state: running
    wait_timeout: 60
  register: base_webserver

- name: Commit webservers to inventory file
  lineinfile:
    path: inventory
    insertafter: '^\[webservers\]\n'
    line: >-
      base_webserver
      ansible_host={{ base_webserver.instances[0].public_dns_name }}
      ansible_user=ec2-user
      ansible_ssh_common_args="'-o StrictHostKeyChecking=no'"
      ansible_ssh_private_key_file=.keypairs/webservers_key.pem
    state: present
- meta: refresh_inventory

- name: Get base webserver facts
  ec2_instance_info:
    filters:
      instance-state-name: ['pending', 'running', 'stopped']
      tag:Name: BaseWebserver
  register: base_webserver

- name: Cleanup facts file
  file:
    path: facts/base_webserver.yml
    state: absent

- name: Store facts to YAML
  lineinfile:
    path: facts/base_webserver.yml
    create: yes
    line: "{{ base_webserver | to_nice_yaml(indent=2) }}"