- name: Install Docker
  package:
    name: docker
    state: latest

- name: Use Docker without sudo
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: Start Docker service
  # [Docker bug] Docker service (init process) and/or Ansible's service modules
  # Docker doesn't REALLY start despite successful status, needs task re-run
  shell:
    cmd: service docker start && chkconfig docker on
    warn: no
  # The below script SHOULD be the right one if everything functioned normally
  # systemd:
  #   name: docker
  #   state: started
  #   enabled: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'