- name: Install Docker
  package:
    name: docker
    state: latest

- name: Use Docker without sudo
  user:
    name: ec2-user
    append: yes
    groups:
      - docker

- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'