- name: Add EC2 hosts to runtime
  add_host:
    name: "{{ item }}"
    ansible_host: localhost
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  loop:
    - mac1
    - mac2
  register: inv
  tags: ['up', 'down']

- name: Commit webservers to inventory
  lineinfile:
    path: inventory
    insertafter: '^\[webservers\]'
    line: >-
      {{ item.add_host.host_name }}
      ansible_host={{ item.add_host.host_vars.ansible_host }}
      ansible_connection={{ item.add_host.host_vars.ansible_connection }}
      ansible_python_interpreter={{ item.add_host.host_vars.ansible_python_interpreter }}
    state: present
  loop: "{{ inv.results }}"
  tags: ['up']

- name: Remove webservers from inventory
  lineinfile:
    path: inventory
    insertafter: '^\[webservers\]'
    line: >-
      {{ item.add_host.host_name }}
      ansible_host={{ item.add_host.host_vars.ansible_host }}
      ansible_connection={{ item.add_host.host_vars.ansible_connection }}
      ansible_python_interpreter={{ item.add_host.host_vars.ansible_python_interpreter }}
    state: absent
  loop: "{{ inv.results }}"
  tags: ['down']

- meta: refresh_inventory