- name: Wait for SSH connection
  wait_for_connection:
    delay: 5
    timeout: 90

- name: Update system packages
  package:
    name: '*'
    state: latest
    update_only: yes

- name: Install Git
  package:
    name: git
    state: latest